const productList = [
  {
    name: "Saffron Road Crunchy Chickpeas, Bombay Spice, 6 Ounce",
    image:
      "https://images-na.ssl-images-amazon.com/images/I/919XjnRNITL._SY500_.jpg",
    desc: "At Saffron Road, we’ve added our own spin to the ancient protein-rich legume—as a satisfying crunch seasoned with carefully blended spices from around the world. Sprinkle them in a salad, toss them in snack mix, pop them in your mouth—the sky’s the limit with these delicious, guilt-free little bites",
    price: "279",
    brand: "Saffron Road",
    inStock: false,
    fastDelivery: false,
    ratings: 4.1,
    offer: "3% discount",
    asinId: "B00E3KJA18",
  },
  {
    name: "Organic Turmeric Root Powder",
    image: "https://m.media-amazon.com/images/I/71pk-eYhE5S._SY500_.jpg",
    desc: "Add some spice to your day with our organic turmeric root powder. This easily recognizable, vibrant yellow-orange powder has long been a staple in South Asian and Middle Eastern cuisines. Commonly used for curries, the root vegetable is also great in soups and stews, or sprinkled over some scrambled eggs.",
    price: "669",
    brand: "FGO",
    inStock: true,
    fastDelivery: true,
    ratings: 4.6,
    offer: "7% discount",
    asinId: "B01CRXAYKS",
  },
  {
    name: "Amrita High Protein Mini Bars",
    image: "https://m.media-amazon.com/images/I/71KJXTQ6g7L._SX569_.jpg",
    desc: "Apple Cinnamon High Protein Bites have the perfect blend of refreshing apples and heartwarming cinnamon. The classic taste and aroma of these two main ingredients are a real homey treat just like mom's apple pie!",
    price: "799",
    brand: "Amrita",
    inStock: true,
    fastDelivery: false,
    ratings: 3.2,
    offer: "10% discount",
    asinId: "B076MJSWFF",
  },
  {
    name: "Vegan Hot Cereal with Superfood Grains, Quinoa, Oats and Amaranth",
    image: "https://images-na.ssl-images-amazon.com/images/I/510W%2BLZjFPL.jpg",
    desc: "Earnest Eats is about believing in nutrition density vs. calorie density; whole food ingredients vs. little bitty bits. This hot and healthy cereal is perfect to start your day to feed your taste buds, body and spirit.",
    price: "419",
    brand: "Earnest Eats",
    inStock: true,
    fastDelivery: false,
    ratings: 4.1,
    offer: "6% discount",
    asinId: "B00A13DPDU",
  },
  {
    name: "Dark Chocolate Nuts & Sea Salt",
    image:
      "https://images-na.ssl-images-amazon.com/images/I/71TEqRNZpSL._SX522_.jpg",
    desc: "KIND Dark Chocolate Nuts & Sea Salt bars are satisfying gluten free bars packed with nuts and the taste of dark chocolate that you can take anywhere. These KIND nut bars lead with heart healthy almonds as the #1 ingredient. This healthy snack bar combines quality ingredients like almonds, dark chocolate, and sea salt to deliver a delicious taste with a little crunch. KIND bars Dark Chocolate Nuts & Sea Salt contain 5 grams of sugar, 6 grams of protein. This KIND nut bar is also gluten free, has a low glycemic index, and is made without genetically engineered ingredients.",
    price: "2299",
    brand: "KIND",
    inStock: true,
    fastDelivery: true,
    ratings: 4.7,
    offer: "5% discount",
    asinId: "B007PE7ANY",
  },
  {
    name: "SKINNYDIPPED Dark Chocolate Covered Almonds",
    image:
      "https://images-na.ssl-images-amazon.com/images/I/71OL0kUBTcL._SX679_.jpg",
    desc: "Are you a health nut? We are. Our SkinnyDipped Almonds are made with nothing but real, clean, delicious ingredients. Each almond is whole roasted with a hint of maple sugar and a touch of sea salt. Next, they are SkinnyDipped in a thin layer of ethically sourced artisan dark chocolate, so you get more almond in every bite and just enough chocolate to make your day sweeter. Last, but not least, each almond is dusted with a hint of espresso. Almonds are known for their high level of nutrients, making SkinnyDipped Almonds an indulgent, yet healthy snacking option. Each serving is packed with plant based protein, fiber, healthy fats, magnesium, antioxidants, and Vitamin E. Our shareable, resealable bags allow you to bring SkinnyDipped Almonds wherever life may take you!",
    price: "999",
    brand: "Espresso",
    inStock: true,
    fastDelivery: true,
    ratings: 4.6,
    offer: "2% discount",
    asinId: "B077G1KJJV",
  },
  {
    name: "Bubly Sparkling Water, Strawberry",
    image:
      "https://images-na.ssl-images-amazon.com/images/I/715jj1aRW0L._SX679_PIbundle-18,TopRight,0,0_AA679SH20_.jpg",
    desc: "Oh hi! bubly sparkling water combines refreshing, crisp sparkling water with great tasting, natural flavors (8 to be exact!) perfect for any occasion. No calories, no sweeteners, all smiles.",
    price: "1549",
    brand: "Bubly",
    inStock: false,
    fastDelivery: true,
    ratings: 4.6,
    offer: "4% discount",
    asinId: "B078ZW6RXK",
  },
  {
    name: "Super Seed Crackers",
    image:
      "https://images-na.ssl-images-amazon.com/images/I/819ZCxTKDZL._SX679_.jpg",
    desc: "Introducing Mary's new super seed line, an extended family of our surprisingly indulgent crackers for all who like a little extra. Packed with seeds and essential fats, our super seed crackers bring new flavors and abundant goodness to your delicious life.",
    price: "999",
    brand: "Mary's Gone Crackers",
    inStock: true,
    fastDelivery: true,
    ratings: 4.4,
    offer: "6% discount",
    asinId: "B01GQ5H8AW",
  },
  {
    name: "RXBAR, Protein Bar",
    image: "https://images-na.ssl-images-amazon.com/images/I/51AZCHK5zGL.jpg",
    desc: "When you want just a little bit of everything, get it with a hand-picked a box filled with our six favorite flavors.",
    price: "2299",
    brand: "RXBAR",
    inStock: true,
    fastDelivery: false,
    ratings: 4.5,
    offer: "3% discount",
    asinId: "B018H3LFJG",
  },
  {
    name: "SkinnyPop Original Popcorn",
    image:
      "https://images-na.ssl-images-amazon.com/images/I/81WZyBbLnEL._SX679_PIbundle-12,TopRight,0,0_AA679SH20_.jpg",
    desc: "Original-flavored popcorn starts with a premium popcorn kernel, sunflower oil and the perfect amount of salt for delicious snacking any time of day. With just 39 calories per cup, this popcorn offer a tasty, guilt-free way to satisfy your hunger. Non-GMO ingredients are free of gluten, dairy, peanuts and preservatives.",
    price: "1099",
    brand: "SkinnyPop",
    inStock: true,
    fastDelivery: true,
    ratings: 4.7,
    offer: "2% discount",
    asinId: "B00KE1EB3W",
  },
  {
    name: "Apple Cider Vinegar Capsules",
    image:
      "https://images-na.ssl-images-amazon.com/images/I/71uacvdwmuL._AC_SY679_.jpg",
    desc: "Apple cider vinegar has been a tonic used by thousands of humans for many years. If you have ever tried it, you know two things. First, it works! Second, it tastes absolutely terrible! Zeal Naturals designed one of the very first apple cider vinegar capsules to provide all the benefits of traditional liquid apple cider vinegar without the nasty taste. Our capsules are easy to swallow for daily balance and cleanliness for your body.",
    price: "3599",
    brand: "Zeal Naturals",
    inStock: false,
    fastDelivery: true,
    ratings: 4.2,
    offer: "7% discount",
    asinId: "B07B6SYTNQ",
  },
  {
    name: "Nature Made Vitamin D3",
    image:
      "https://images-na.ssl-images-amazon.com/images/I/71oXmvph46L._AC_SX679_.jpg",
    desc: "Say hello to an easy and effective Vitamin D supplement to support muscle, bone, teeth, and immune health. Vitamin D3 is more effective at raising and maintaining adequate levels of Vitamin D throughout the body. Vitamin D is a common nutrient shortfall. Support your Vitamin D dietary needs today, with Nature Made’s Vitamin D 1000 IU softgels.",
    price: "1999",
    brand: "Nature Made",
    inStock: true,
    fastDelivery: true,
    ratings: 4.8,
    offer: "4% discount",
    asinId: "B004U3Y8OM",
  },
  {
    name: "AS-IT-IS Nutrition Whey Protein",
    image:
      "https://images-na.ssl-images-amazon.com/images/I/514DjbvLP5L._SX679_.jpg",
    desc: "AS-IT-IS Whey is undenatured and is manufactured by cold-processing keeping in consideration to preserve the nutritional values, biological and functional properties of Whey. Our fast-digesting, high quality Whey dissolves quickly in water and is rapidly digested to help you reap the benefits of your workout by flooding crucial amino acids required for muscle repair and muscle regrowth. Whey Protein Concentrate is the most-efficient and economic protein available on the market today & provides 80% protein per serving.",
    price: "999",
    brand: "Asitis Nutrition",
    inStock: true,
    fastDelivery: true,
    ratings: 4,
    offer: "5% discount",
    asinId: "B079SZJJDR",
  },
  {
    name: "OZiva Plant Based Biotin",
    image:
      "https://images-na.ssl-images-amazon.com/images/I/61XA084huDS._SX679_.jpg",
    desc: "OZiva Plant Based Biotin is India’s First Whole Food Biotin extracted from 100% Natural Sesbania Agati leaves. It improves immunity, stamina, glucose intolerance, energy metabolism, healthy blood cells, active lifestyle, neural health, etc. with Biotin. Natural, plant-based source of Biotin i.e. Sesbania Extract standardized to 0.5% Biotin unlike other biotin products in the market that use synthetic isolates created wholly in a lab from industrial chemicals and solvents.",
    price: "699",
    brand: "OZiva",
    inStock: true,
    fastDelivery: true,
    ratings: 3.9,
    offer: "5% cashback",
    asinId: "B07VQHJ3FF",
  },
  {
    name: "OZiva Hair Vitamins",
    image:
      "https://images-na.ssl-images-amazon.com/images/I/61COdkO1G2S._SX679_.jpg",
    desc: "OZiva Hair Vitamins is an advanced formula of Hair Vitamins, DHT Blocker, and Omega 3 formulated specially to provide daily hair nutrition. Promotes hair growth and nourishment with the goodness of Vitamin A, C, D, E, B-complex, Iron, Zinc, etc & Omega 3. Prevents follicle shrinking and controls hair fall with the help of DHT Blockers like Stinging Nettle, Pumpkin Seed, Beta-Sitosterol, and Pine Bark.",
    price: "899",
    brand: "OZiva",
    inStock: true,
    fastDelivery: true,
    ratings: 3.9,
    offer: "5% instant discount",
    asinId: "B0861TV6VX",
  },
  {
    name: "Protinex Health And Nutritional Drink",
    image:
      "https://images-na.ssl-images-amazon.com/images/I/71s2SiX4vPL._SX679_.jpg",
    desc: "Protinex Tasty Chocolate is a vegetarian ready to serve beverage mix that helps bridge the gap of nutrients from diet of Indian Adults. Protinex Tasty Chocolate is an adult nutritional drink mix that is clinically proven to provide 34% higher immuno boosters that help build immunity. Protinex contains 22 essential vitamins and minerals including 10 immuno nutrients that help build immunity, build strength, and provide energy. Protinex consists of nutrients that help in building bone strength, growth & maintenance of muscle mass, improving metabolism, formation of blood cells, and maintaining fluid & electrolyte balance. Available in chocolate flavor, Protinex easily makes its place in your everyday diet plan, and with zero added sugar and low fat, it is suitable for daily consumption.",
    price: "499",
    brand: "Protinex",
    inStock: true,
    fastDelivery: true,
    ratings: 4.3,
    offer: "5% instant discount",
    asinId: "B01MS489AE",
  },
  {
    name: "Bournvita Health Drink Pouch",
    image:
      "https://images-na.ssl-images-amazon.com/images/I/71en2Xly%2B8L._SX466_.jpg",
    desc: "It contains Protein (which helps in maintenance and growth of muscle mass), Vitamin B12/B2 (which is essential for maintaining a normal function of the nervous system) and Iodine/Iron (which support normal cognitive functions.",
    price: "299",
    brand: "Cadbury Bournvita",
    inStock: true,
    fastDelivery: false,
    ratings: 4.4,
    offer: "3% instant discount",
    asinId: "B06XSFGDK6",
  },
  {
    name: "Pintola All Natural Peanut Butter",
    image:
      "https://images-na.ssl-images-amazon.com/images/I/71gi0ilTrqL._SY741_.jpg",
    desc: "PINTOLA's All Natural Peanut Butter is made up from the finest grade, fresh, crunchy and nutritious Peanuts from an ISO 22000, HACCP and BRC Certified Factory.this VALUE PACK is specially introduced for gym goer and students staying in hostels to get quick healthy breakfast every morning.It also for food outlets those make peanut butter flavor of sandwiches and ice-cream.No Hydrogenated Oils.",
    price: "399",
    brand: "Pintola",
    inStock: true,
    fastDelivery: true,
    ratings: 4.4,
    offer: "2% instant discount",
    asinId: "B06XFVG7R8",
  },
  {
    name: "Quinoa - Breakfast Cereal",
    image:
      "https://images-na.ssl-images-amazon.com/images/I/61HirhQ-KqL._SX569_.jpg",
    desc: "True Elements quinoa dates back three to four thousand years ago and was known as the mother of the super grains back then because it used to increase the stamina of the warriors and today nutritionist call it as super grain. True Elements quinoa is high in protein content, has sweet and nutty flavour and delicate texture, a great substitute to starchier pasta and rice. True Elements gluten free quinoa is an easy grain to love.",
    price: "329",
    brand: "True Elements",
    inStock: true,
    fastDelivery: false,
    ratings: 4.3,
    offer: "4% instant discount",
    asinId: "B01LEMUGFG",
  },
  {
    name: "Organic Raw Apple Cider Vinegar",
    image:
      "https://images-na.ssl-images-amazon.com/images/I/81dveRX0DzL._SX679_.jpg",
    desc: "WOW Life Science Apple Cider Vinegar is pure, unfiltered, undiluted & unpasteurized Apple Cider Vinegar with genuine mother of vinegar content. It is made from fermenting the real apple juice (not concentrate) - extracted from the finest of Himalayan apples; in order to obtain the maximum health, wellness and beauty benefits.",
    price: "450",
    brand: "WOW",
    inStock: true,
    fastDelivery: true,
    ratings: 4.2,
    offer: "5% instant discount",
    asinId: "B01AC9G656",
  },
];

module.exports = { productList };
