export const initialState = {
  productList: [],
  cartList: [],
  wishList: [],
  sortBy: "",
  showOutOfStock: false,
  showFastDeliveryOnly: false,
  search: "",
  showToast: false,
  toastMessage: "",
  selectedBrands: [],
  brands: [],
  priceRange: 10000,
  firstname: "",
  lastname: "",
};
